version: '3.8'

services:
  back:
    image: back
    container_name: example-back
    restart: unless-stopped 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      # REQUEST_ORIGIN: http://localhost:80
    depends_on:
      - db
    ports:
      - 8080:8080

  front:
    image: front
    container_name: example-front
    restart: unless-stopped 
    # environment:
    #   REQUEST_ORIGIN: http://localhost:80
    ports:
      - 5000:5000  

  example-redis:
    image: redis
    container_name: example-redis
    restart: unless-stopped 
    ports: 
      - 6379:6379
     
  db: 
    image: postgres
    container_name: db
    restart: unless-stopped 
    volumes: 
      - db28:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80

volumes:
  db28:
    driver: local

